trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: test  

steps:
- powershell: |
    "the value: $(secret)" | Out-File -FilePath  $(Build.ArtifactStagingDirectory)\DisplaySecret.txt
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'



